### ISSUE TITLE
Eine weitere Festplatte kann nicht installiert werden

### ISSUE THREAD

**Issue by felixinx** [gcWorld/IBIScontrol-Bugs#24]
Sorry für mein Deutsch

Das Plugin kann nicht auf eine andere Festplatte (G: \) installiert werden.

This plugin can't be installed in another drive, for example G:\ .
.NET ERROR;
![net error](https://cloud.githubusercontent.com/assets/8009156/6997677/785675b6-db93-11e4-8ce0-97fa1b0d2c8e.png)
See my [Pastebin](http://pastebin.com/g4LDTMB9).

Sorry but is in french ):

Thanks

**Comment by gcWorld** [comment]
Actually, there has to be a different problem, on my setup OMSI is installed on a different drive (E:), no problems here.

Can you check whether the following path actually exists?
E:\SteamLibrary\steamapps\common\OMSI 2\plugins

**Comment by felixinx** [comment]
There is no E:\ path, my G:\ drive is an external drive. It was E:\ before, but it was disconnected and now is G:\
I will try to launch OMSI from Steam and not directly from the EXE.

**Comment by gcWorld** [comment]
Ah I see. 
The Updater reads the registry for the path to the OMSI directory. The actual path changed but the registry was not updated. Thus the updater is unable to locate the correct path.
Let me see if I can include a manual way to provide the path to the OMSI directory.

**Comment by gcWorld** [comment]
New Updater version is available now (1.1.0.0). Please let me know if this does not fix your problem.

**Comment by felixinx** [comment]
Sorry for the delay.
It's works! Thanks!
