### ISSUE TITLE
Could you upload the plugin source code

### ISSUE THREAD

**Issue by Plaigon** [gcWorld/IBIScontrol-Bugs#38]
Hello gcWorld, I try in despair for few days to run my OMSI plugin coded in Delphi, but pointlessly, nothing wants to work, logs tells me " LoadLibrary failed ", would it be possible to have your source code so that I can correct mine, or by uploading mine, can you correct it ? Thank you in advance ! =)

**Comment by gcWorld** [comment]
Hey, 
Is this for OMSI 1 or 2?
The log should give you more error details than just the "loadlibrary failed".

**Comment by Plaigon** [comment]
This is for OMSI 2. 
Here is my log file:
https://pastebin.com/c1PH3vbP
Here is my delphi code
https://pastebin.com/CGqCyAQD
And form unit file:
https://pastebin.com/UVabGmgu

To clarify my problem, i should say you that this plugin rewritten in C++ is perfectly working.
Another thing, i have to tell you is that OMSI main menu is not accessible, because of this error message: "Zugriffsverletzung bei Adresse 0054BBAF in Modul 'Omsi.exe' Schreiben von Adresse 00000000.".

Of course, the plugin is a 32 bits dll, and compiled with Lazarus ide. Thanks in advance for you quick answer =)

**Comment by gcWorld** [comment]
You're missing the necessary functions.

    57 15:36:08 -  -     Warning:       Loading plugin plugins\Project1.dll: procedure "AccessVariable" not found!
    58 15:36:08 -  -     Warning:       Loading plugin plugins\Project1.dll: procedure "AccessTrigger" not found!
    59 15:36:08 -  -     Warning:       Loading plugin plugins\Project1.dll: procedure "AccessSystemVariable" not found!
    60 15:36:08 -  -     Warning:       Loading plugin plugins\Project1.dll: procedure "AccessStringVariable" not found!

Take a look at this example code. It's in German and mostly deals with OMSI 1, but the last chapter also contains the necessary changes for OMSI 2.
http://www.man-stadtbus.de/wiki/index.php?title=Plug-in-Schnittstelle

**Comment by Plaigon** [comment]
https://pastebin.com/rGnZCATT
Unfortunately, with this new code, the same error always persists in the starting up. Would not you think that we would win of time(weather) if you showed me the source code of one of your plugins, to compare with mine? Thank you in advance!

**Comment by gcWorld** [comment]
Here you go:
https://gist.github.com/gcWorld/62b5162fab4a15f79e3a79a1bb454bb3

**Comment by Plaigon** [comment]
Thanks a much for your upload. But when i'm using your same "uses" content, the Lazarus IDE consoles tells me that System.SysUtils couldn't have been found. Do you use Lazarus as Delphi ide, or another one ? 
Another thing to note is that my dll compiled file weighs 15 372 Ko, for me it's supposed to be too much than yours, right ?
And why are you speaking me about ShareMem, i don't see that in your code, please must i put it into my code ?

**Comment by gcWorld** [comment]
I think the ShareMem comment was placed there automatically. It is not relevant from what I understand as there are no procedures exporting any strings.

I'm using the Delphi XE 10.2 IDE (free). I did have trouble making it work with Lazarus myself so I can't help you with any specifics there. 

The file size was similar to yours initially. Try building it as a release build as opposed to a debug build, that should bring down the size.

**Comment by Plaigon** [comment]
Please do you have a download link for Delphi XE 10.2 IDE ? I keep getting results about Embarcadero, which is paying :/

**Comment by gcWorld** [comment]
You are looking for the starter edition which is free.
https://www.embarcadero.com/products/delphi/starter

**Comment by Plaigon** [comment]
Then, I have just made a new test, this time under the ide Embarcadero. Here is the new code: 
https://pastebin.com/GywyJsMR
But nothing can be done, always the same error which occurs :/
Maybe that my installation of OMSI is the cause, you could thus test this plugin yourself, in your own OMSI directory ? The link to download: http://www.mediafire.com/file/i3e61km3qbcm69d/Project1.dll
Do you have to change other parameters in the configuration of the ide, or no?
Thank you in advance!

**Comment by Plaigon** [comment]
All is working, just by coping/pasting your code. Thanks a lot for your patience & skills =)

**Comment by gcWorld** [comment]
That's great. Thanks for the feedback.

**Comment by Plaigon** [comment]
Just what is the difference between AccessVariable, AccessSystemVariable and AccessStringVariable functions ? Thanks in advance ! =)
