### ISSUE TITLE
Error starting the IBIScontrol_1.3.0.exe

### ISSUE THREAD

**Issue by estebansiyoesteban** [gcWorld/IBIScontrol-Bugs#42]
I have the Omsi 2, but not purchased from the Steam Store. So when i open up the setup it says me this error message "The installation of IBIScontrol requires Omsi 2 to be installed. Install Omsi 2 before this modification. The setup will be terminated", so i think it may be setup program detect the omsi from the steam folders so i moved up my omsi files to the carpet were i have my games, but didn't work.

Does this happen to anyone else?

What can I do to solve this?

Greetings from Chile, I'm sorry if I wrote something wrong but I gave all my best English ;)

**Comment by gcWorld** [comment]
The setup program is looking for the OMSI 2 path entry within the registry. I only have the Steam version, but it is very possible that other version set a different registry key. Where have you purchased the game from?

In the meantime you can grab the .zip file and place the two files into the OMSI 2 plugin folder manually:
https://github.com/gcWorld/IBIScontrol-Bugs/releases/download/1.2.2/IBIScontrol-1.3.zip

**Comment by gcWorld** [comment]
Considering this one solved for now. Feel free to open this again if there are any remaining issues.
