### ISSUE TITLE
IBISControl als echtes IBIS für Traditionsbus 3680

### ISSUE THREAD

**Issue by LillyWho** [gcWorld/IBIScontrol-Bugs#43]
Hallo!

Ich wollte fragen, ob es möglich und/oder erlaubt wäre, den IBISControl Server für einen Raspberry Pi zu adaptieren, um einen (zum Beispiel) Web-Clienten als echtes IBIS zu benutzen.

Hintergrundgeschichte:

Traditionsbus 3680 ist ein MAN D88 SD202 und wurde von der BVG mit einem Fahrscheindrucker (ALMEX) und einem Fahrgastinformationssystem ausgerüstet. Nun ist dieses Infosystem nur leider sehr zickig und hängt sich gerne auf. Es wird vermutet, dass ein Radsensor defekt ist, aber es liegt schon eigentlich alleine an der Elektronik/Software.
Hier meine Idee:

Raspberry Pi mit einem Touchscreen und passendem Gehäuse ausstatten
In das Lautsprechersystem verdrahten
IBISControl API Benutzen, um eigenes Ansagensystem und IBIS UI auf dem RasPi laufen zu lassen und Fahrern ein traditionelles IBIS mit automatischen Ansagen (zB via GPS) zu bieten.

Wie klingt die Idee?

Lg Lilly

Der Bus: https://www.traditionsbus.de/Fahrzeuge/d_88.htm

**Comment by gcWorld** [comment]
Moin,

das Projekt klingt auf jeden Fall interessant. Ich bin mir allerdings nicht ganz sicher wie IBIScontrol dazu passt.
IBIScontrol ist speziell auf OMSI zugeschnitten und enthält selbst kaum nennenswerte Logik um ein IBIS unabhängig von OMSI simulieren zu können.
Gerade das Plugin (Server) dient nur zum Austausch von Informationen zwischen Android App und OMSI.

Andersherum könnte ich es eher sehen. Sprich die Android App als IBIS UI nutzen und an einen Raspberry Pi anbinden zwecks IBIS Logik, Ansage System, GPS, ...

Da ist es dann aber vermutlich auch eine Überlegung wert es gleich komplett auf dem Pi umzusetzen. Das wäre auf jeden Fall ein reizvolles Projekt, und könnte dann letztendlich ja wieder auch zusätzlich mit OMSI funktionieren.

Das sind so erstmal meine Gedanken hierzu.
